# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52d65160d4ff2b38fad3084531c6248320375b4821e704b394bc1fc0acbfa93caed74a99d9b11eeb33f813cf36f315e703b7b34f3ea931cb9153567923501cf5
  facebook_api_id: 160480944336991
  facebook_api_secret: c692fc12ea6d666b3d0682417497a413
  twitter_api_id: <%= ENV["TWITTER_API_ID"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>
  google_api_id: <%= ENV["GOOGLE_API_ID"] %>
  google_api_secret: <%= ENV["GOOGLE_API_SECRET"] %>

test:
  secret_key_base: e4dfde8a4ac1f9b257af3e709c8a6544f6896bbbd8f0804f120c47a836220236e0ea158b793de6e67c6e0c2be2d197c5f367e9160648d85547286199856d5f05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_api_id: <%= ENV["FACEBOOK_API_ID"] %>
  facebook_api_secret: <%= ENV["FACEBOOK_API_SECRET"] %>
  twitter_api_id: <%= ENV["TWITTER_API_ID"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>
  google_api_id: <%= ENV["GOOGLE_API_ID"] %>
  google_api_secret: <%= ENV["GOOGLE_API_SECRET"] %>
